#!/usr/bin/env bash

pushd $(dirname $BASH_SOURCE)

if [[ -n "$(docker-compose ps -q)" ]]; then
    echo "Service already running" >&2
    exit 1
fi

docker-compose up --build -d
docker-compose exec db mysqladmin -uroot --wait=10 ping
docker-compose exec db mysqladmin -uroot create fluxbb
